name: joaopina
favicon: null
layout_spectrum: 0.99957
typography_spectrum: 0.42754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0717178441118449
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5110233745072037
purpose: []
